version: '3.8'

services:
  web:
    build:
      context: .
    command: >
      bash -c "cd mysite && python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/codeForDev
    ports:
      - "8012:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - EMAIL_HOST=smtp
      - EMAIL_PORT=1025
      - EMAIL_USE_TLS=False
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}