version: '3.8'

services:
  web:
    build: ./mysite
    command: ["./entrypoint.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8012:8000"
    volumes:
      - ./mysite:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - EMAIL_HOST=smtp
      - EMAIL_PORT=1025
      - EMAIL_USE_TLS=False
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=zzbc1234
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - loki

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - loki

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - loki

  celery:
    build: ./mysite
    command: celery -A mysite worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./mysite:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - loki

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - ./mysite/logs:/app/logs 
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki

  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - loki

volumes:
  postgres_data:
  grafana_data:

networks:
  loki: 