apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
      - name: mysite-container
        image: ghcr.io/kuenway/mysite:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
          - name: DB_HOST
            value: postgres-service
          - name: DB_PORT
            value: "5432"
          - name: DB_URL
            value: "postgres://postgres:postgres@$(DB_HOST):5432/postgres"
          - name: EMAIL_HOST
            value: smtp
          - name: EMAIL_PORT
            value: "1025"
          - name: EMAIL_USE_TLS
            value: "False"
          - name: EMAIL_HOST_USER
            value: c51470086@gmail.com
          - name: EMAIL_HOST_PASSWORD
            value: xjyf dntz psxn fuvd
          - name: DJANGO_SUPERUSER_USERNAME
            value: admin
          - name: DJANGO_SUPERUSER_EMAIL
            value: admin@example.com
          - name: DJANGO_SUPERUSER_PASSWORD
            value: zzbc1234
          - name: CELERY_BROKER_URL
            value: redis://redis:6379/0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery-container
          image: ghcr.io/kuenway/mysite:latest
          env:
            - name: CELERY_BROKER_URL
              value: redis://redis:6379/0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
          - name: GF_PATHS_PROVISIONING
            value: /etc/grafana/provisioning
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Admin
          - name: GF_SERVER_ROOT_URL
            value: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
          - name: GF_SERVER_SERVE_FROM_SUB_PATH
            value: "true"
        volumeMounts:
          - name: grafana-storage
            mountPath: /var/lib/grafana
          - name: grafana-provisioning
            mountPath: /etc/grafana/provisioning
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-provisioning
          configMap:
            name: grafana-provisioning
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
data:
  ds.yaml: |
    apiVersion: 1
    datasources:
      - name: PostgreSQL
        type: postgres
        access: proxy 
        orgId: 1
        url: http://postgres-service:5432
        database: postgres
        user: postgres
        password: postgres
        isDefault: true
        version: 1
        editable: false
