# Generated by Django 4.0.2 on 2024-05-26 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='require_info',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('factory', models.CharField(max_length=5)),
                ('priority', models.CharField(max_length=15)),
                ('lab', models.CharField(max_length=20)),
                ('current_priority', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
