# Generated by Django 4.0.2 on 2024-05-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='require_info',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('factory', models.CharField(max_length=5)),
                ('priority', models.CharField(max_length=15)),
                ('lab', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
