# Generated by Django 4.0.2 on 2024-05-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='require_info',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
