# Generated by Django 4.0.2 on 2024-05-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cn', '0002_alter_require_info_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='require_info',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
