name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up environment
      run: |
        docker-compose build
        docker-compose up -d
        docker-compose exec web python manage.py makemigrations
        docker-compose exec web python manage.py migrate
        docker-compose exec web python manage.py test web_cn

    - name: Generate coverage report
      run: |
        docker-compose exec web python manage.py test web_cn
        # docker-compose exec web coverage run manage.py test web_cn
        # docker-compose exec web coverage report
      working-directory: ./mysite


