name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up Independencies for coverage report
      run: |
        python -m pip install --upgrade pip
        pip install coverage

    # - name: Set up Node.js
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '16'

    - name: Generate coverage report
      run: |
        coverage run manage.py test web_cn
        coverage report
      working-directory: ./mysite


